apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockyards-git
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dockyards-git
      app.kubernetes.io/part-of: dockyards
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dockyards-git
        app.kubernetes.io/part-of: dockyards
      name: dockyards-git
    spec:
      containers:
      - args:
        - --git-project-root=/git
        - --repository-hostname=dockyards-git.$(METADATA_NAMESPACE).svc.cluster.local
        env:
        - name: METADATA_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: dockyards-git
        name: dockyards-git
        ports:
        - name: public
          containerPort: 9002
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: git-repositories
          mountPath: /git
      volumes:
      - name: git-repositories
        emptyDir: {}
      imagePullSecrets:
      - name: dockyards-registry
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: dockyards-git
