apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: dockyards-git
  name: dockyards-git
spec:
  ports:
  - name: git
    port: 80
    protocol: TCP
    targetPort: 9002
  selector:
    app.kubernetes.io/name: dockyards-git
