run:
  timeout: 5m
  tests: false
linters:
  enable:
  - goconst
  - govet
  - importas
  - nestif
  - nlreturn
  - reassign
  - revive
  - usestdlibvars
  - whitespace
linters-settings:
  importas:
    no-unaliased: true
    alias:
    - pkg: k8s.io/api/core/v1
      alias: corev1
    - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
      alias: metav1
    - pkg: bitbucket.org/sudosweden/dockyards-backend/pkg/api/v1alpha3
      alias: dockyardsv1
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
