image: docker.io/library/golang:1.23.0

definitions:
  steps:
  - step: &default
      name: default
      script:
      - echo "export VERSION=$(git branch --show-current)-$(git rev-parse --short HEAD)-$(date +%s)" >> env.sh
      - echo "export IMAGE=public.ecr.aws/sudosweden/dockyards-git" >> env.sh
      - echo "export REVISION=$(git branch --show-current)@$(git rev-parse --show-object-format):$(git rev-parse HEAD)" >> env.sh
      artifacts:
      - env.sh
  - step: &vendor
      name: vendor
      script:
      - go mod vendor
      artifacts:
      - vendor/**
  - step: &build
      name: build
      script:
      - source env.sh
      - go install cuelang.org/go/cmd/cue@v0.7.1
      - docker build . --file Containerfile --tag dockyards-git
      - docker save dockyards-git --output dockyards-git.tar
      - cue eval hack/kustomization.cue --inject "name=$IMAGE" --inject "tag=$VERSION" --out yaml --outfile config/kustomization.yaml
      services:
      - docker
      caches:
      - docker
      artifacts:
      - dockyards-git.tar
      - config/kustomization.yaml
  - step: &push
      name: push
      script:
      - source env.sh
      - cat ecr-login-password | docker login --username AWS --password-stdin public.ecr.aws
      - docker load --input dockyards-git.tar
      - docker tag dockyards-git "${IMAGE}:${VERSION}"
      - docker push "${IMAGE}:${VERSION}"
      services:
      - docker
  - step: &ecr-login
      name: login
      image: docker.io/amazon/aws-cli:2.15.2
      oidc: true
      script:
      - echo $BITBUCKET_STEP_OIDC_TOKEN > /tmp/web-identity-token
      - aws configure --profile bitbucket set region us-east-1
      - aws configure --profile bitbucket set role_arn arn:aws:iam::075899289117:role/BitbucketPipelinesDockyardsGitPublic
      - aws configure --profile bitbucket set web_identity_token_file /tmp/web-identity-token
      - aws ecr-public get-login-password --profile bitbucket > ecr-login-password
      artifacts:
      - ecr-login-password
  - step: &flux
      name: flux
      image: ghcr.io/fluxcd/flux-cli:v2.2.3
      script:
      - source env.sh
      - flux push artifact "oci://$IMAGE:$VERSION-manifests" --path config --source "$BITBUCKET_GIT_HTTP_ORIGIN" --revision "$REVISION" --creds "AWS:$(cat ecr-login-password)"
      services:
      - docker
  - step: &tag
      name: tag
      script:
      - echo "export VERSION=$(git describe --exact-match)" >> env.sh
      - echo "export IMAGE=public.ecr.aws/sudosweden/dockyards-git" >> env.sh
      - echo "export REVISION=$(git branch --show-current)@$(git rev-parse --show-object-format):$(git rev-parse HEAD)" >> env.sh
      artifacts:
      - env.sh
  - step: &lint
      name: lint
      script:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.0
      - golangci-lint run

pipelines:
  default:
  - step: *default
  - step: *vendor
  - step: *lint
  - step: *build
  - step: *ecr-login
  - step: *push
  - step: *flux
  tags:
    'v*':
    - step: *tag
    - step: *vendor
    - step: *lint
    - step: *build
    - step: *ecr-login
    - step: *push
    - step: *flux
