---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dockyards-git
rules:
- apiGroups:
  - dockyards.io
  resources:
  - worktrees
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dockyards.io
  resources:
  - worktrees/status
  verbs:
  - patch
