---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dockyards-git
rules:
- apiGroups:
  - dockyards.io
  resources:
  - containerimagedeployments
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - dockyards.io
  resources:
  - containerimagedeployments/status
  verbs:
  - patch
- apiGroups:
  - dockyards.io
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dockyards.io
  resources:
  - kustomizedeployments
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - dockyards.io
  resources:
  - kustomizedeployments/status
  verbs:
  - patch
